namespace: backend-app

image:
  repository: agida0413/backend-member
  tag: latest
  pullPolicy: Always

replicaCount: 2

labels:
  partOf: backend-part
  component: backend-member
  name: backend-member-pod-name
  instance: backend-member-pod-instance
  version: "1.0.0"
  managedBy: kubectl

containerPort: 8080

resources:
  limits:
    memory: "200Mi"
    cpu: "200m"
  requests:
    memory: "100Mi"
    cpu: "100m"

readinessPath: /actuator/health/readiness
livenessPath: /actuator/health/liveness

envFrom:
  configMap: backend-member-config
  secret: backend-member-secret

service:
  name: backend-member-service
  port: 80
  targetPort: 8080
  selector: *labels

hpa:
  enabled: true
  name: backend-member-hpa
  targetDeployment: backend-member-pod
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization: 70
  memoryUtilization: 70
