pipeline {
    agent any

    tools {
        gradle 'gradle-8.3'
        jdk 'jdk-17'
    }

    environment {
        APP_GITHUB_URL = 'https://github.com/testkimyj0413/test-2.git'
        APP_VERSION = '0.0.1'
    }

    stages {
        stage('소스파일 체크아웃') {
            steps {
                git branch: 'develop', url: "${APP_GITHUB_URL}"
            }
        }

        stage('소스 빌드') {
            steps {
                // 755권한 필요 (윈도우에서 Git으로 소스 업로드시 권한은 644)

                sh "chmod +x ./gradlew"
                sh "gradle clean build -x test"
            }
        }

        stage('릴리즈파일 체크아웃') {
            steps {
                 checkout([$class: 'GitSCM',
                           branches: [[name: 'main']],
                           userRemoteConfigs: [[url: "${RELEASE_GITHUB_URL}"]]
                 ])
            }
        }


        stage('넥서스 배포') {
            ./gradlew publish
        }

}
