apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa  # HPA 리소스 이름
  namespace: default
spec:
  scaleTargetRef:            # 어떤 리소스를 스케일링할 것인가?
    apiVersion: apps/v1
    kind: Deployment         # Deployment, StatefulSet 등
    name: my-app             # 대상 리소스 이름 (ex. deployment 이름)
  minReplicas: 2             # 최소 파드 수
  maxReplicas: 10            # 최대 파드 수
  metrics:
    - type: Resource         # 리소스 기반 (CPU, memory 등)
      resource:
        name: cpu
        target:
          type: Utilization  # 평균 CPU 사용률을 기준
          averageUtilization: 50  # CPU 평균 사용률이 50%를 넘으면 scale up
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60