FROM openjdk:17
COPY build/libs/project-dev-0.0.1-SNAPSHOT.jar /usr/src/myapp/project-dev-0.0.1-SNAPSHOT.jar
WORKDIR /usr/src/myapp
ENTRYPOINT ["java", "-Dspring.profiles.active=dev", "-jar", "/usr/src/myapp/project-dev-dev-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080