apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-member-pod
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
      containers:
        - name: backend-member-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ .Values.envFrom.configMap }}
            - secretRef:
                name: {{ .Values.envFrom.secret }}
#          readinessProbe:
#            httpGet:
#              path: "{{ .Values.readinessPath }}"
#              port: {{ .Values.containerPort }}
#            periodSeconds: 10
#            failureThreshold: 3
#          livenessProbe:
#            httpGet:
#              path: "{{ .Values.livenessPath }}"
#              port: {{ .Values.containerPort }}
#            periodSeconds: 10
#            failureThreshold: 3
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
